-- 고객정보 CUSTOMER
CREATE TABLE CUSTOMER(
    USER_NUMBER NUMBER(10) PRIMARY KEY,
    USER_ID VARCHAR2(8) UNIQUE CHECK(LENGTH(USER_ID)<=8 AND LENGTH(USER_ID)>=5),
    USER_PW VARCHAR2(12) CHECK(LENGTH(USER_PW)<=12 AND LENGTH(USER_PW)>=8),
    NAME VARCHAR2(20) NOT NULL,
    RRN CHAR(13) UNIQUE,
    CREDIT_SCORE NUMBER(4) NOT NULL,
    PHONE_NUM CHAR(13),
    EMAIL VARCHAR2(30),
    JOB VARCHAR2(15) NOT NULL,
    INCOME NUMBER(10) NOT NULL,
    BANK VARCHAR2(10) NOT NULL,
    ACCOUNT NUMBER(20) NOT NULL,
    PREF NUMBER(1) NOT NULL
);

-- DROP TABLE CUSTOMER;

-- 대출 상품 LOAN_PRODUCT
CREATE TABLE LOAN_PRODUCT (
  PRODUCT_NUMBER NUMBER(10) PRIMARY KEY,
  LOAN_PRODUCT VARCHAR2(50) NOT NULL,
  BANK_NAME VARCHAR2(20),
  RATE NUMBER(5),
  MAX_LOAN NUMBER(10),
  MAX_MONTH NUMBER(2),
  PRODUCT_JOB VARCHAR2(15) NOT NULL
);

-- 고객 대출 정보 LOAN_INFO
CREATE TABLE LOAN_INFO(
  LOAN_NUMBER NUMBER(10) PRIMARY KEY,
  USER_NUMBER NUMBER(10) REFERENCES CUSTOMER(USER_NUMBER),
  NAME VARCHAR2(20) NOT NULL,
  PRODUCT_NUMBER NUMBER(10) REFERENCES LOAN_PRODUCT(PRODUCT_NUMBER),
  LOAN_PRODUCT VARCHAR2(50),
  RATE NUMBER(5),
  MAX_LOAN NUMBER(10),
  MAN_MONTH NUMBER(2),
  PERIOD NUMBER(2)
);

-- 게시판 목록 BOARD
CREATE TABLE BOARD (
  BOARD_NUMBER NUMBER(10) PRIMARY KEY,
  BOARD_NAME VARCHAR2(30) UNIQUE 
);

-- 고객의 소리(게시판) WRITE
CREATE TABLE WRITE (
  WRT_NUM NUMBER(10) PRIMARY KEY,
  BOARD_NAME VARCHAR2(30) REFERENCES BOARD(BOARD_NAME),
  TITLE VARCHAR2(30) NOT NULL,
  CONTENTS VARCHAR2(50),
  WRT_DATE DATE,
  USER_ID VARCHAR2(8) REFERENCES CUSTOMER(USER_ID)
);

-- 댓글 REPLY
CREATE TABLE REPLY (
COMMENT_NUM NUMBER(10) PRIMARY KEY,
WRT_NUM NUMBER(10) REFERENCES WRITE(WRT_NUM),
COMMNET_CON VARCHAR2(50),
USER_ID VARCHAR2(8) REFERENCES CUSTOMER(USER_ID)
);