-- 대출 상품
CREATE TABLE LOAN_PRODUCT (
  PRODUCT_NUMBER NUMBER(10) PRIMARY KEY,
  LOAN_PRODUCT VARCHAR2(50) NOT NULL,
  BANK_NAME VARCHAR2(20),
  RATE NUMBER(5),
  MAX_LOAN NUMBER(10),
  MAX_MONTH NUMBER(2),
  PRODUCT_JOB VARCHAR2(15) NOT NULL
);