-- 고객 대출 정보
CREATE TABLE LOAN_INFO(
  LOAN_NUMBER NUMBER(10) PRIMARY KEY,
  USER_NUMBER NUMBER(10) REFERENCES CUSTOMER(USER_NUMBER),
  NAME VARCHAR2(20) NOT NULL,
  PRODUCT_NUMBER NUMBER(10) REFERENCES LOAN_PRODUCT(PRODUCT_NUMBER),
  LOAN_PRODUCT VARCHAR2(50),
  RATE NUMBER(5),
  MAX_LOAN NUMBER(10),
  MAN_MONTH NUMBER(2),
  PERIOD NUMBER(2)
);

