-- 고객의 소리(게시판)
CREATE TABLE WRITE (
  WRT_NUM NUMBER(10) PRIMARY KEY,
  BOARD_NAME VARCHAR2(30) REFERENCES BOARD(BOARD_NAME),
  TITLE VARCHAR2(30) NOT NULL,
  CONTENTS VARCHAR2(50),
  WRT_DATE DATE,
  USER_ID VARCHAR2(8) REFERENCES CUSTOMER(USER_ID)
);